name: Scala Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Coursier
      run: |
        curl -Lo cs https://github.com/coursier/coursier/releases/download/v2.1.0/cs-x86_64-pc-linux-generic
        chmod +x cs
        mv cs $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install sbt using Coursier
      run: cs install sbt --home $HOME/.sbt

    - name: Add sbt to PATH
      run: echo "$HOME/.sbt/bin" >> $GITHUB_PATH

    - name: Set up sbt
      run: sbt update

    - name: Build with sbt
      run: sbt compile

    - name: Run tests
      run: sbt test
